name = "Sunrise Hub"
license = "MIT"
licenselink = "https://github.com/sunrise-bay-area/sunrise-bay-area/blob/master/themes/sunrise-hub/LICENSE"
description = ""
homepage = "https://sunrisebayarea.org"
tags = []
features = []
min_version = "0.41"

[author]
  name = ""
  homepage = ""
