name: Hugo Staging

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2.4.9
    
    - name: deploy
      if: job.status == 'success' && github.event == 'pull_request'
      uses: appleboy/scp-action@master
      with:
        host: sunrisemovement.dev
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.key }}
        target: /srv/sunrisemovement.dev/sfbay/public
        source: public/*
